FROM golang:1.14 as builder
WORKDIR /go/src/app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app

FROM alpine:3.12
COPY --from=builder /go/bin/app /go/bin/app
RUN adduser --system --disabled-password --no-create-home myapp
ENV DB_HOST=localhost
USER myapp
CMD sh -c "sleep 10 && /go/bin/app"
